### PR TITLE
Universal macOS Binary on last Xcode version + FR translation

### PR DESCRIPTION
**Pull request by skylex**
Builds on Xcode 13.2.1 without any warning.
Tested both builds (ARM and Intel via Rosetta) with all sample NFOs and it works perfectly on Apple Silicon (M1 Pro).
I'm french and I used TextEdit's menus as a reference for the french translation of the menus.

### CODE REVIEW

**Comment by mackonsti** [comment]
Salut @skylex et merci. Thank you for your code and version update.
Can you please provide me your new build so I can package it as a release?
**I will mention you in my main page if you accept !**
Does it still work well with your NFO files you tested? The TTF too?
As mentioned in my main page, I have not touched it for years 😄 
Thank you very much for your contribution.

**Comment by skylex** [comment]
Here you go, a simple dmg file containing the compiled app as Universal Binary (link valid for 7 days) :
https://send.bitwarden.com/#mmXSGWXac0aHJK5QAPGhgg/rHwJSGZfoDpFkoMKle-Nyg
Yes everything works as it should.
No need to mention me on the main page.
Thank you for you work on this very useful app !

**Comment by mackonsti** [comment]
As you wish @skylex but I insist on mentioning your kind contribution.
Please stick around, I'd be happy to work with you, as you are most likely the only person still being able to check the code and compile, my skills were left back when Xcode 3 was around 🤣 
Merci et à bientôt.

**Comment by mackonsti** [comment]
Merci @skylex it's now published 👍

**Pull request merged**
